module.exports = {
	userService: require("./user.service"),
	notificationServices: require("./notification.service"),
	walletServices: require("./wallet.service"),
	assetService: require("./asset.service"),
	managerService: require("./manager.service"),
	auctionService: require("./auction.service"),
	transactionService: require("./transaction.service"),
	languageService: require("./language.service"),
	cardService: require("./card.service"),
	managerLogService: require("./managerLog.service"),
	competitionService: require("./competition.service"),
	prizeService: require("./manager/prize/prize.service"),
	tokenPrizeService: require("./manager/prize/token-prize.service"),
	assetNetworkServices: require("./assetNetwork.service"),
	networkServices: require("./network.service"),
	ticketService: require("./ticket.service"),
	departmentService: require("./department.service"),
	cardTypeService: require("./manager/cardType/cardType.service"),
	authService: require("./auth.service"),
	tokenService: require("./token.service"),
	statisticService: require("./statistics.service"),
	countryService: require("./country.service"),
	attributeService: require("./attribute.service"),
	boxService: require("./manager/box/box.service"),
	swapService: require("./swap.service"),
};
