module.exports = {
	userController: require("./user.controller"),
	walletController: require("./wallet.controller"),
	assetController: require("./asset.controller"),
	managerController: require("./manager.controller"),
	auctionController: require("./auction.controller"),
	transactionController: require("./transaction.controller"),
	publicController: require("./public.controller"),
	languageController: require("./language.controller"),
	cardController: require("./card.controller"),
	managerLogController: require("./managerLog.controller"),
	competitionController: require("./competition.controller"),
	prizeController: require("./manager/prize/prize.controller"),
	tokenPrizeController: require("./manager/prize/tokenPrize.controller"),
	assetNetworkController: require("./assetNetwork.controller"),
	networkController: require("./network.controller"),
	ticketController: require("./ticket.controller"),
	departmentController: require("./department.controller"),
	cardTypeController: require("./manager/cardType/cardType.controller"),
	authController: require("./auth.controller"),
	tokenController: require("./token.controller"),
	countryController: require("./country.controller"),
	attributeController: require("./attribute.controller"),
	boxController: require("./manager/box/box.controller"),
	swapController: require("./swap.controller"),
	swapV2Controller: require("./v2/Swap/swap.controller"),
	boxV2Controller: require("./v2/public/box.controller"),
};
